name: Feature deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build docker image
        run: ./gradlew shadowJar
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vovochkastelmashchuk/good-readme
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/heads/') }}
